server:
  port: 8761
eureka:
  client:
    # 自己本来就是注册中心，不需要自己注册自己
    register-with-eureka: false
    fetch-registry: false
    # 通过查看源码知道 service-url是个map, 默认的key是 defaultZone
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
  #这是server端自我检测,自我保护模式,在开发的时候,可以关闭,就当做没有这回事,不然看到红字就敏感
    enable-self-preservation: false
spring:
  application:
    name: eurekaServer