
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/shenghe_game/config-repo.git
          username: shenghe_game@163.com
          password: shenghe2017
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
server:
  port: 8100

