spring:
  application:
    name: enrekaConsumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
server:
  port: 8004
management:
  endpoints:
    web:
      exposure:
        exclude: hysgtrix.stream
      base-path: /

turbine:
  app-config: eurekaServer,eurekaProducer
  aggregator:
    cluster-config: default
  cluster-name-expression: new String( "default")
